trigger:
- master

variables:
  initVsShell: 'call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\vsdevcmd" -arch=x64'

stages:
- stage: Build

  ####################
  # Ninja
  ####################

  jobs:
  - job: Ninja
    timeoutInMinutes: 0
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - script: choco install ninja
      displayName: Install Ninja

    - script: >
        $(initVsShell) && powershell -command "& cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -G Ninja -S . -B build"
      displayName: CMake

    - script: >
        $(initVsShell) && powershell -command "& cmake --build build"
      displayName: Build

  ####################
  # macOS
  ####################

  - job: AppleClang
    timeoutInMinutes: 0
    pool:
      vmImage: 'macos-10.13'

    steps:
    - task: CMake@1
      inputs:
        cmakeArgs: '-DCMAKE_BUILD_TYPE=Release ..'

    - script: make -j
      workingDirectory: build
      displayName: Build
